#!/bin/sh
set -e


cat > ci/vars <<-EOF
export BUILD_DATE=$(date +%Y%m%dT%H%M)
export VCS_REF=$(git rev-parse --short HEAD)
export ALPINE_TAG=alpine-\${BUILD_DATE}-git-\${VCS_REF}
EOF

. ci/vars

docker-compose build
